# https://cloud.google.com/build/docs/building/build-containers#use-buildconfig
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/cloudbuild-yaml/gcp-cloudrun-python3-gunicorn:2.0.0', '.' ]
