# https://cloud.google.com/build/docs/building/build-containers#use-buildconfig
# https://cloud.google.com/build/docs/build-config-file-schema#images

# Docker build and tag
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$_GAR_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPO/$REPO_NAME:$TAG_NAME', '.' ]

# Docker push so TAG_NAME can be used in next step
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_GAR_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPO/$REPO_NAME:$TAG_NAME' ]

# deploy to GCP Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - run
  - deploy
  - $REPO_NAME
  - --image
  - '$_GAR_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPO/$REPO_NAME:$TAG_NAME'
  - --region=$_GAR_REGION
  - --set-env-vars=VERSION=TAG$TAG_NAME
  - --ingress=all
  - --allow-unauthenticated
  - --execution-environment=gen2
  - --no-use-http2
  - --quiet

# push all these images
images:
- $_GAR_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPO/$REPO_NAME:$TAG_NAME

#options:
#  logging: CLOUD_LOGGING_ONLY
substitutions:
  _GAR_REGION: us-east1
  _GAR_REPO: my-gar-repo
