# https://cloud.google.com/build/docs/building/build-containers#use-buildconfig
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$_GAR_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPO/$REPO_NAME:$COMMIT_SHA', '.' ]
images:
- $_GAR_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPO/$REPO_NAME:$COMMIT_SHA
- $_GAR_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPO/$REPO_NAME:latest

#options:
#  logging: CLOUD_LOGGING_ONLY

# default substitutions that will be used unless we override with '--substitutions' flag
substitutions:
  _GAR_REGION: us-east1
  _GAR_REPO: my-gar-repo
